spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.222.226.44:1521/UFIS.dca.com
    username: ceda
    password: x2_CpgSpqV9yky
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle
    show-sql: true